language: node_js
node_js:
- 8
cache:
  directories:
  - node_modules
branches:
  only:
  - master
before_script:
- npm install -g firebase-tools
script:
- npm test
- npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token: $FIREBASE_TOKEN
  project: $PROJECT_ID
before_install:
- openssl version
- openssl aes-256-cbc -K $encrypted_8c73dede5511_key -iv $encrypted_8c73dede5511_iv -in firebaseConfig2.js.enc -out ./src/firebase/firebaseConfig2.js -d
