language: node_js
node_js:
  - "node"
cache:
  directories:
  - node_modules #Cache node_modules for faster builds
script:
  - npm test #Runs Tests
  - npm run build #Creats a production build
deploy:
  provider: firebase
  token:
    secure: $firebase_token
  project: "my-line-today"